FROM debian:bookworm

RUN apt update -y && apt install mariadb-server -y

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/mariadb.sh /mariadb.sh

RUN chmod +x /mariadb.sh

EXPOSE 3306

CMD [ "/mariadb.sh" ]
