# listening port for the FTP server
listen=YES
listen_ipv6=NO

# disable anonymous login
anonymous_enable=NO

# enable local users to log in
local_enable=YES

# allow users to upload files
write_enable=YES

# set umask for uploaded files
local_umask=022

# allow users to be restricted to their home directories
chroot_local_user=YES
allow_writeable_chroot=YES

# enable passive mode and set the port range
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# set the passive mode address to localhost
pasv_address=127.0.0.1
