# listening port for the FTP server
listen=YES
listen_ipv6=NO

# disable anonymous login
anonymous_enable=NO

# enable local users to log in
local_enable=YES

# Permissions & Chroot
write_enable=YES
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES

# Docker Passive Mode Networking
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=sel-abbo.42.fr
